config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "events#index"
  # Routes for the Review resource:

  # CREATE
  get("/reviews/new", { :controller => "reviews", :action => "new_form" })
  post("/create_review", { :controller => "reviews", :action => "create_row" })
  post("/create_review_from_event", { :controller => "reviews", :action => "create_row_from_event" })

  # READ
  get("/reviews", { :controller => "reviews", :action => "index" })
  get("/reviews/:id_to_display", { :controller => "reviews", :action => "show" })

  # UPDATE
  get("/reviews/:prefill_with_id/edit", { :controller => "reviews", :action => "edit_form" })
  post("/update_review/:id_to_modify", { :controller => "reviews", :action => "update_row" })

  # DELETE
  get("/delete_review/:id_to_remove", { :controller => "reviews", :action => "destroy_row" })
  get("/delete_review_from_event/:id_to_remove", { :controller => "reviews", :action => "destroy_row_from_event" })
  get("/delete_review_from_member/:id_to_remove", { :controller => "reviews", :action => "destroy_row_from_member" })

  #------------------------------

  # Routes for the Genre resource:

  # CREATE
  get("/genres/new", { :controller => "genres", :action => "new_form" })
  post("/create_genre", { :controller => "genres", :action => "create_row" })

  # READ
  get("/genres", { :controller => "genres", :action => "index" })
  get("/genres/:id_to_display", { :controller => "genres", :action => "show" })

  # UPDATE
  get("/genres/:prefill_with_id/edit", { :controller => "genres", :action => "edit_form" })
  post("/update_genre/:id_to_modify", { :controller => "genres", :action => "update_row" })

  # DELETE
  get("/delete_genre/:id_to_remove", { :controller => "genres", :action => "destroy_row" })

  #------------------------------

  # Routes for the Attendance resource:

  # CREATE
  get("/attendances/new", { :controller => "attendances", :action => "new_form" })
  post("/create_attendance", { :controller => "attendances", :action => "create_row" })
  post("/create_attendance_from_event", { :controller => "attendances", :action => "create_row_from_event" })

  # READ
  get("/attendances", { :controller => "attendances", :action => "index" })
  get("/attendances/:id_to_display", { :controller => "attendances", :action => "show" })

  # UPDATE
  get("/attendances/:prefill_with_id/edit", { :controller => "attendances", :action => "edit_form" })
  post("/update_attendance/:id_to_modify", { :controller => "attendances", :action => "update_row" })

  # DELETE
  get("/delete_attendance/:id_to_remove", { :controller => "attendances", :action => "destroy_row" })
  get("/delete_attendance_from_event/:id_to_remove", { :controller => "attendances", :action => "destroy_row_from_event" })
  get("/delete_attendance_from_member/:id_to_remove", { :controller => "attendances", :action => "destroy_row_from_member" })

  #------------------------------

  # Routes for the Interest resource:

  # CREATE
  get("/interests/new", { :controller => "interests", :action => "new_form" })
  post("/create_interest", { :controller => "interests", :action => "create_row" })
  post("/create_interest_from_event", { :controller => "interests", :action => "create_row_from_event" })

  # READ
  get("/interests", { :controller => "interests", :action => "index" })
  get("/interests/:id_to_display", { :controller => "interests", :action => "show" })

  # UPDATE
  get("/interests/:prefill_with_id/edit", { :controller => "interests", :action => "edit_form" })
  post("/update_interest/:id_to_modify", { :controller => "interests", :action => "update_row" })

  # DELETE
  get("/delete_interest/:id_to_remove", { :controller => "interests", :action => "destroy_row" })
  get("/delete_interest_from_event/:id_to_remove", { :controller => "interests", :action => "destroy_row_from_event" })
  get("/delete_interest_from_user/:id_to_remove", { :controller => "interests", :action => "destroy_row_from_user" })

  #------------------------------

  # Routes for the Event resource:

  # CREATE
  get("/events/new", { :controller => "events", :action => "new_form" })
  post("/create_event", { :controller => "events", :action => "create_row" })
  post("/create_event_from_genre", { :controller => "events", :action => "create_row_from_genre" })

  # READ
  get("/events", { :controller => "events", :action => "index" })
  get("/events/:id_to_display", { :controller => "events", :action => "show" })

  # UPDATE
  get("/events/:prefill_with_id/edit", { :controller => "events", :action => "edit_form" })
  post("/update_event/:id_to_modify", { :controller => "events", :action => "update_row" })

  # DELETE
  get("/delete_event/:id_to_remove", { :controller => "events", :action => "destroy_row" })
  get("/delete_event_from_genre/:id_to_remove", { :controller => "events", :action => "destroy_row_from_genre" })
  get("/delete_event_from_user/:id_to_remove", { :controller => "events", :action => "destroy_row_from_user" })

  #------------------------------

  devise_for :members
  # Routes for the Member resource:

  # READ
  get("/members", { :controller => "members", :action => "index" })
  get("/members/:id_to_display", { :controller => "members", :action => "show" })

  #------------------------------

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/attendance_templates/_attendances_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "attendances_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :member_email_cont, "Member email contains" %>
    <%= f.text_field :member_email_cont, :class => "form-control", :placeholder => "Member email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :event_name_cont, "Event name contains" %>
    <%= f.text_field :event_name_cont, :class => "form-control", :placeholder => "Event name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/attendances" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#attendances_filters">
  Show filters
</a>

app/views/attendance_templates/edit_form.html.erb
<h1>
  Edit attendance #<%= @attendance.id %>
</h1>

<hr>

<form action="/update_attendance/<%= @attendance.id %>" method="post">


  <div class="form-group">
    <label for="event_id">
      Event
    </label>

    <%= select_tag(:event_id, options_from_collection_for_select(Event.all, :id, :name, @attendance.event_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update attendance
  </button>
</form>

<hr>

<a href="/attendances">
  Go back
</a>

app/views/attendance_templates/edit_form_with_errors.html.erb
<% if @attendance.errors.any? %>
  <% @attendance.errors.full_messages.each do |message| %>
    <div class="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<h1>
  Edit attendance #<%= @attendance.id %>
</h1>

<hr>

<form action="/update_attendance/<%= @attendance.id %>" method="post">


  <div class="form-group">
    <label for="event_id">
      Event
    </label>

    <%= select_tag(:event_id, options_from_collection_for_select(Event.all, :id, :name, @attendance.event_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update attendance
  </button>
</form>

<hr>

<a href="/attendances">
  Go back
</a>

app/views/attendance_templates/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      All attendances
    </h1>

    <a href="/attendances/new" class="btn btn-block btn-outline-secondary">
      Add a new attendance
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "attendance_templates/attendances_search_form" %>
  </div>
</div>



<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>
          ID
        </th>

        <th>
          Member
        </th>

        <th>
          Event
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @attendances.each do |attendance| %>
      <tr>
        <td>
          <%= attendance.id %>
        </td>

        <td>
          <% if attendance.member.present? %>
            <a href="/members/<%= attendance.member.id %>">
              <%= attendance.member.email %>
            </a>
          <% end %>
        </td>

        <td>
          <% if attendance.event.present? %>
            <a href="/events/<%= attendance.event.id %>">
              <%= attendance.event.name %>
            </a>
          <% end %>
        </td>

        <td>
          <%= time_ago_in_words(attendance.created_at) %> ago
        </td>

        <td>
          <%= time_ago_in_words(attendance.updated_at) %> ago
        </td>

        <td>
          <a href="/attendances/<%= attendance.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>

    <div class="row mb-3">
      <div class="col-md-12">
        <%= paginate @attendances, theme: "twitter-bootstrap-4" %>
      </div>
    </div>

  </div>
</div>

app/views/attendance_templates/new_form.html.erb
<h1>
  Add a new attendance
</h1>


<hr>

<form action="/create_attendance" method="post">

  <input type="hidden" name="member_id" value="<%= current_member.id %>">

  <div class="form-group">
    <label for="event_id">
      Event
    </label>

    <%= select_tag(:event_id, options_from_collection_for_select(Event.all, :id, :name, @attendance.event_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create attendance
  </button>
</form>

<hr>

<a href="/attendances">
  Go back
</a>

app/views/attendance_templates/new_form_with_errors.html.erb
<% if @attendance.present? %>
  <% if @attendance.errors.any? %>
    <% @attendance.errors.full_messages.each do |message| %>
      <div class="alert alert-danger">
        <%= message %>
      </div>
    <% end %>
  <% end %>
<% end %>

<h1>
  Add a new attendance
</h1>


<hr>

<form action="/create_attendance" method="post">

  <input type="hidden" name="member_id" value="<%= current_member.id %>">

  <div class="form-group">
    <label for="event_id">
      Event
    </label>

    <%= select_tag(:event_id, options_from_collection_for_select(Event.all, :id, :name, @attendance.event_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create attendance
  </button>
</form>

<hr>

<a href="/attendances">
  Go back
</a>

app/views/attendance_templates/show.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <h1>
      Attendance #<%= @attendance.id %> details
    </h1>

    <div class="row mb-3">
      <div class="col">
        <a href="/attendances" class="btn btn-block btn-outline-secondary">
          Go back
        </a>
      </div>

      <div class="col">
        <% if current_member == @attendance.member %>
          <a href="/attendances/<%= @attendance.id %>/edit" class="btn btn-block btn-sm btn-outline-secondary">
            Edit attendance
          </a>
        <% end %>
      </div>

      <div class="col">
        <% if current_member == @attendance.member %>
          <a href="/delete_attendance/<%= @attendance.id %>" class="btn btn-block btn-sm btn-outline-secondary">
            Delete attendance
          </a>
        <% end %>
      </div>
    </div>

    <dl>
      <dt>
        Member
      </dt>
      <dd>
        <% if @attendance.member.present? %>
          <a href="/members/<%= @attendance.member_id %>">
            <%= @attendance.member.email %>
          </a>
        <% end %>
      </dd>

      <dt>
        Event
      </dt>
      <dd>
        <% if @attendance.event.present? %>
          <a href="/events/<%= @attendance.event_id %>">
            <%= @attendance.event.name %>
          </a>
        <% end %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@attendance.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@attendance.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>